// <auto-generated />
using AuthorizationServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace AuthorizationServer.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20171011233151_AddUserName")]
    partial class AddUserName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("AuthorizationServer.Models.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .HasColumnName("client_id");

                    b.Property<int>("IsStop")
                        .HasColumnName("is_stop");

                    b.Property<string>("Token")
                        .HasColumnName("refresh_token");

                    b.Property<string>("UserName")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("token");
                });
#pragma warning restore 612, 618
        }
    }
}
